version: "3.8"
services:
  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management interface port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # React Frontend Service
  frontend:
    build:
      context: ./frontend # Path to your React app
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_RABBITMQ_WS_URL=ws://localhost:15672/ws
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
